ALTER TABLE usuarios CHANGE password_hash password VARCHAR(128) NOT NULL;
ALTER TABLE usuarios CHANGE nombre username VARCHAR(150) NOT NULL;
ALTER TABLE usuarios ADD COLUMN first_name VARCHAR(150) NOT NULL DEFAULT '';
ALTER TABLE usuarios ADD COLUMN last_name VARCHAR(150) NOT NULL DEFAULT '';
ALTER TABLE usuarios ADD COLUMN is_staff TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE usuarios ADD COLUMN is_active TINYINT(1) NOT NULL DEFAULT 1;
ALTER TABLE usuarios ADD COLUMN is_superuser TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE usuarios ADD COLUMN last_login DATETIME(6) DEFAULT NULL;
ALTER TABLE usuarios ADD COLUMN date_joined DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);
